-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 01:57:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CateKids
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CateKids` ;

-- -----------------------------------------------------
-- Schema CateKids
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CateKids` DEFAULT CHARACTER SET utf8 ;
USE `CateKids` ;

-- -----------------------------------------------------
-- Table `CateKids`.`Parroquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Parroquia` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Parroquia` (
  `idParroquia` INT NOT NULL AUTO_INCREMENT,
  `NombreParroquia` VARCHAR(45) NOT NULL,
  `Direccion` TEXT NOT NULL,
  `Parroco` VARCHAR(45) NOT NULL,
  `Decanato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idParroquia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Nivel` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Nivel` (
  `idNivel` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `idParroquia` INT NOT NULL,
  PRIMARY KEY (`idNivel`),
  INDEX `FK_NivelParroquia_idx` (`idParroquia` ASC) VISIBLE,
  CONSTRAINT `FK_NivelParroquia`
    FOREIGN KEY (`idParroquia`)
    REFERENCES `CateKids`.`Parroquia` (`idParroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Horario` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `HorarioEntrada` TIME NOT NULL,
  `HorarioSalida` TIME NOT NULL,
  `Salon` VARCHAR(45) NOT NULL,
  `Dia_reunion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Catequista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Catequista` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Catequista` (
  `idCatequista` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(18) NOT NULL,
  `sexo` CHAR NOT NULL,
  PRIMARY KEY (`idCatequista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `idNivel` INT NOT NULL,
  `idCatequista` INT NOT NULL,
  `idHorario` INT NOT NULL,
  `idParroquia` INT NOT NULL,
  `fechaInicioCurso` DATE NOT NULL,
  `fechaTerminoCurso` DATE NOT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `FK_GrupoHorario_idx` (`idHorario` ASC) VISIBLE,
  INDEX `FK_GrupoNivel_idx` (`idNivel` ASC) VISIBLE,
  INDEX `FK_GrupoCatequista_idx` (`idCatequista` ASC) VISIBLE,
  INDEX `FK_GrupoParroquia_idx` (`idParroquia` ASC) VISIBLE,
  CONSTRAINT `FK_GrupoNivel`
    FOREIGN KEY (`idNivel`)
    REFERENCES `CateKids`.`Nivel` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GrupoHorario`
    FOREIGN KEY (`idHorario`)
    REFERENCES `CateKids`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GrupoCatequista`
    FOREIGN KEY (`idCatequista`)
    REFERENCES `CateKids`.`Catequista` (`idCatequista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_GrupoParroquia`
    FOREIGN KEY (`idParroquia`)
    REFERENCES `CateKids`.`Parroquia` (`idParroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `idParroquia` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `FK_UsuarioParroquia_idx` (`idParroquia` ASC) VISIBLE,
  CONSTRAINT `FK_UsuarioParroquia`
    FOREIGN KEY (`idParroquia`)
    REFERENCES `CateKids`.`Parroquia` (`idParroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`PadreTutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`PadreTutor` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`PadreTutor` (
  `idPadreTutor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPadreTutor`),
  INDEX `FK_UsuarioTutor_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_UsuarioTutor`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `CateKids`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(18) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `sexo` CHAR NOT NULL,
  `idPadreTutor` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `FK_AlumnoTutor_idx` (`idPadreTutor` ASC) VISIBLE,
  CONSTRAINT `FK_AlumnoTutor`
    FOREIGN KEY (`idPadreTutor`)
    REFERENCES `CateKids`.`PadreTutor` (`idPadreTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`AlumnosGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`AlumnosGrupo` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`AlumnosGrupo` (
  `idAlumnosGrupo` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaTermino` DATE NULL,
  PRIMARY KEY (`idAlumnosGrupo`),
  INDEX `FK_AlumnoGrupo1_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `FK_AlumnoGrupo2_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `FK_AlumnoGrupo1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `CateKids`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AlumnoGrupo2`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `CateKids`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`BitacoraRegistros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`BitacoraRegistros` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`BitacoraRegistros` (
  `idBitacoraRegistros` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `tipoMovimiento` VARCHAR(45) NOT NULL,
  `Tabla` VARCHAR(45) NOT NULL,
  `FechaMov` DATETIME NOT NULL,
  `Descripcion` TEXT NOT NULL,
  PRIMARY KEY (`idBitacoraRegistros`),
  INDEX `FK_BitacoraUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `FK_BitacoraUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `CateKids`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Avisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Avisos` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Avisos` (
  `idAvisos` INT NOT NULL AUTO_INCREMENT,
  `idGrupo` INT NOT NULL,
  `idCatequista` INT NOT NULL,
  `Contenido` TEXT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`idAvisos`),
  INDEX `FK_AvisoGrupo_idx` (`idGrupo` ASC) VISIBLE,
  INDEX `FK_AvisoCatequista_idx` (`idCatequista` ASC) VISIBLE,
  CONSTRAINT `FK_AvisoGrupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `CateKids`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AvisoCatequista`
    FOREIGN KEY (`idCatequista`)
    REFERENCES `CateKids`.`Catequista` (`idCatequista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`Documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`Documentos` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`Documentos` (
  `idDocumentos` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `nombreDocumento` VARCHAR(45) NOT NULL,
  `rutaDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `FK_DocAlumno_idx` (`idAlumno` ASC) VISIBLE,
  CONSTRAINT `FK_DocAlumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `CateKids`.`Alumno` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CateKids`.`DomicilioTutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CateKids`.`DomicilioTutor` ;

CREATE TABLE IF NOT EXISTS `CateKids`.`DomicilioTutor` (
  `idDomicilioTutor` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `idPadreTutor` INT NOT NULL,
  PRIMARY KEY (`idDomicilioTutor`),
  INDEX `FK_DomicilioTutor_idx` (`idPadreTutor` ASC) VISIBLE,
  CONSTRAINT `FK_DomicilioTutor`
    FOREIGN KEY (`idPadreTutor`)
    REFERENCES `CateKids`.`PadreTutor` (`idPadreTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
